<a href="https://colab.research.google.com/github/adi-thyan03/DataAcquisitionCaseStudy/blob/main/Data_Acquisition_casestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv("/content/Data-Science-Jobs.csv")

In [3]:
df.head()

,Position,Job Title,Company Name,Location,Salary,Date,Logo,Job Link,Company Rating
0,1,Associate Stop Loss Underwriter,The Insurance Center\n2.7,"Onalaska, WI",$57K - $84K (Glassdoor est.),30d+,https://media.glassdoor.com/sql/453835/the-ins...,https://www.glassdoor.com/partner/jobListing.h...,2.7
1,2,Manager of Data Science,"Nuvative, Inc.\n3.4","Wichita, KS",$106K - $157K (Glassdoor est.),30d+,https://media.glassdoor.com/sql/1384674/net-pa...,https://www.glassdoor.com/partner/jobListing.h...,3.4
2,3,Senior Data Product Manager,ProviderTrust\n4.2,"Nashville, TN",$105K - $141K (Glassdoor est.),11d,https://media.glassdoor.com/sql/1953857/hibob-...,https://www.glassdoor.com/partner/jobListing.h...,4.2
3,4,Oncology Nurse Navigator,Inizio Engage\n3.6,"Portland, OR",$90K - $113K (Employer est.),1d,https://media.glassdoor.com/sql/8794153/inizio...,https://www.glassdoor.com/partner/jobListing.h...,3.6
4,5,Head of Artificial Intelligence – Americas Region,Covestro\n3.6,"Pittsburgh, PA",$89K - $148K (Glassdoor est.),30d+,https://media.glassdoor.com/sql/27128/covestro...,https://www.glassdoor.com/partner/jobListing.h...,3.6

Print the summary statistics of the dataset

In [4]:
df.describe()

         Position  Company Rating
count  500.000000      439.000000
mean   250.500000        3.812301
std    144.481833        0.480281
min      1.000000        1.000000
25%    125.750000        3.600000
50%    250.500000        3.800000
75%    375.250000        4.000000
max    500.000000        5.000000

○ Q1: What is the size of the dataset? (Number of rows and columns)

In [ ]:
column_row = df.shape
print("Column :",{column_row[0]})
print("Row :",{column_row[1]})

Column : {500}
Row : {9}

○ Q2: What are the data types of each column?

In [ ]:
df.dtypes

Position            int64
Job Title          object
Company Name       object
Location           object
Salary             object
Date               object
Logo               object
Job Link           object
Company Rating    float64
dtype: object

 Q3: Are there any missing values in the dataset? If so, which columns have missing values and how many?

In [ ]:
df.isnull()

,Position,Job Title,Company Name,Location,Salary,Date,Logo,Job Link,Company Rating
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,True,False,False,False,False
496,False,False,False,False,False,False,True,False,True
497,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,True
499,False,False,False,False,False,False,False,False,False

○ Q4: What are the unique values in a categorical column of your choice? How many unique values are there?

In [ ]:
categorical_column = df['Job Title']

unique_values = categorical_column.unique()

num_unique_values = categorical_column.nunique()

print(f"Unique values in '{categorical_column.name}' column: {unique_values}")
print(f"Number of unique values: {num_unique_values}")

Unique values in 'Job Title' column: ['Associate Stop Loss Underwriter' 'Manager of Data Science'
 'Senior Data Product Manager' 'Oncology Nurse Navigator'
 'Head of Artificial Intelligence – Americas Region' 'IT Manager'
 'Data Center Services Technician - IT, Crypto Mining'
 'Data Center Construction Coordinator' 'Senior AIOps Engineer'
 'Software Measurement and Estimation Analyst' 'Principal Data Scientist'
 'Training Department Supervisor' 'Senior Data Scientist'
 'Space Communications Analyst' 'Machine Learning Engineer'
 'Marketing Advertising Analyst' 'IT Site Engineer (labs)'
 'Sr. Digital Signal Processing Engineer' 'RN Clinical Educator'
 'Senior Predictive Modeler'
 'Data Manager (NetSuite ERP) & Website Content Manager'
 'Senior Software Engineer' 'Legal Assistant' 'Junior Game Mathematician'
 'Senior Data Analyst (Hybrid Remote)'
 'Senior Manager Advanced Analytics (US)' 'AI/ML Subject Matter Expert'
 'Violence Prevention Data Coordinator' 'Lead AI Developer'
 'Business Process Project Manager' 'Commercial Intelligence Developer'
 'Data Scientist - I'
 'Data Scientist - AI, NLP, Python, PyTorch, Tensorflow (W2 Candidates Only - Denver CO)'
 'Data Scientist' 'Data Scientist - Manufacturing Analytics'
 'Project Manager/ Senior Data Analyst' 'Data Science Technical Fellow'
 'Azure Data Architect'
 "$45/hr - AI Trainer - Computer Science Focused - Educational Content Developer (Bachelor's Degree Required)"
 'Artificial Intelligence (AI) Cybersecurity Architect'
 'Marketing Analyst'
 'Director - Systems and Technology - Data, Artificial Intelligence and Portfolio Delivery'
 'AI Integration Specialist' 'Data Analyst (Onsite)'
 'Digital Marketing Specialist (Paid Media Focus)'
 'Sr. Data Science Engineer' 'Statistician'
 'Data Scientist TS/SCI On-site' 'Senior Data Analyst'
 'Senior Research Scientist - Adversarial Machine Learning'
 'Principal Data Scientist - Time Series' 'DATA SCIENTIST / DATA ANALYST'
 'NC3 Systems Engineer - Omaha' 'Sr. Data Analyst'
 'Computational Engineer (Level II or Senior)'
 'Employee Relations Manager'
 'Machine Learning Engineer (Perception and Planning)'
 'Director, Statistical Programming' 'Senior Clinical Informatics Analyst'
 'First ML Hire - Senior ML/NLP Data Scientist and SDE'
 'Patent Agent (Machine Learning AI/Computer Science) - ELITE AMLAW FIRM'
 'Data Scientist – NLP' 'Senior Data Scientist (Remote Available)'
 'Full Stack Data Engineer' 'Senior Statistician' 'Data Analyst'
 'Data Architect III' 'Logistics Data Analyst' 'Statistical Programmer'
 'Data Scientist [Post-Doc Research Fellow]' 'SAP Performance Engineer'
 'Head of Retention Marketing'
 'Space Predictive Modeling and Sim Analyst Mid Level'
 'Business Intelligence Engineer / Data Visualization Engineer'
 'Sr. Data Scientist' 'Sr. Data Architect - Healthcare'
 'Front Desk/Mail Clerk' 'Sr. Analyst, Data Science & Reporting'
 'Cell Therapy Navigators'
 'Software Engineer for AI Training Data (Python)'
 'Reporting Data Engineer' 'Analytical Flavor Chemist'
 'Senior Performance Software Engineer, Deep Learning Libraries'
 'Bilingual (English/Spanish) AI Engineer'
 'Head of R and D Data Engineering' 'Supply Chain Analyst'
 'Solution Developer I - Automation & Innovation Management'
 'Senior Data Science Analyst' 'Data Science Engineer - Remote'
 'Manager - IT Infrastructure Engineering'
 'Quantitative Analytics Senior (Hybrid- 3 Days in Office)'
 'Research Scientist' 'Software Developer'
 'Principal Statistical Programmer' 'Junior Data Science'
 'Director of Asset Management' 'Marketing Campaign Analyst'
 'Principal Data Science' 'Product Management Leader- AI'
 'Manager Data Science' 'Data Governance, VP' 'Data Scientist & Engineer'
 'Data Science Associate, Offers, YouTube Connected TV'
 'Software Engineer for AI Training Data (JavaScript)'
 'Data Science Consultant' 'Data Sciences Associate 24-00049'
 'Lead Data Science Analyst'
 'Quantitative Analytics Professional (Hybrid- 3 Days in Office)'
 'Senior Marketing Data & Automation Analyst'
 'Senior AI-HPC Storage Engineer'
 'Quantitative Analytics Senior (Hybrid - 3 Days in Office)'
 'Field Data Collector (PPC)' 'VP, Portfolio Management Data Science'
 'Sr Financial Data Analyst' 'Data Science' 'Mgr Data Science'
 'Senior Data Pipeline Engineer, AgTech' 'Data Science Trainee'
 'Chief Enterprise Integration Architect' 'Health edge Consultant'
 'Blackstone Data Science Engineering, Associate' 'Data Science Manager'
 'OAG #24-259: Data Miner - Research Data Analyst 1' 'Data Engineer (PO)'
 'Financial Data Analyst' 'Data Scientist / Statistician'
 'Director, Data Science (On-Site)'
 'Data Scientist - Secureworks - Atlanta, GA or Remote, US'
 'Data Mining Analyst - Life Sciences' 'Chief Enterprise Data Architect'
 'OAG #24-196: Data Miner (Research Data Analyst 2)'
 'Chinese OSINT Collector' 'Immunology Key Account Manager'
 'Rapid Deployment Representative' 'Data Science Technical Specialist'
 'Data Platform Business Ownership, AVP' 'Machine Learning Sales Engineer'
 'Lead Sr. Data Engineer | Scientist' 'Vice President, Data Science'
 'Reliability, Availability and Serviceability Expert, Datacenter AI Products Development'
 'Senior Machine Learning Engineer II' 'Back End Developer'
 'Junior Data Analyst' 'Basketball Data Scientist'
 'Community Hub Data Analyst' 'Basketball Data Science & Scheduling Lead'
 'Pharmaceutical Field Sales Representative'
 'Associate, Data Science (Aladdin Engineering)'
 'Senior Director, Data Science & AI - Enabling Functions'
 'Data Science Automation Engineer' 'Engineer, Generative AI'
 'SC&O Data Science' 'Data Science - Optimization'
 'Patent Engineer / Scientist -Seismic/Physics/Applied Math'
 'Senior Specialist, Cloud Data Engineer'
 'Senior Associate, Data Science - Retail Bank'
 'AI/ML Senior System Engineer' 'Model Risk Governance Analyst' 'Modeler'
 'Senior Manager Data Science' 'Sr. Healthcare Data Analyst'
 'Manufacturing Data Analyst' 'Consultant, Data Science (I9)'
 'Data Scientist (Javascript, .Net Framework, SQL)-Remote'
 'Head of Data Science & Machine Learning, Personal Investor'
 'Cleared Scrum Master' 'Manager, Data Science (Remote)'
 'FinTech Data Scientist'
 'Senior Research Data Scientist - Center for Health Data Science & Analytics'
 '$40/hr - $50/hr - AI Trainer - Legal Specialist - Educational Content Developer (JD or LLM Required)'
 'Returnship - Big Data Insights Developer' 'Manager - Data Science'
 'Drone Services Manager' 'AI/ML Engineer'
 'Data Science Summer Bootcamp Instructor'
 'Postdoctoral Scientist - Data Science (Digital Measurement)'
 'Sr Engineer (Data Science)'
 'Quantitative Analytics Senior - Climate Risk (Hybrid - 3 Days in Office)'
 'Data Scientist - Analytics' 'Director, Data Science'
 'Quantitative Analytics Senior Manager (Hybrid- 3 Days in Office)'
 'People Data Analyst'
 'Director, Program Management, Translational & Quantitative Sciences'
 'Data Science Lead - Global Marketing' 'Clinical Data Analyst'
 'Cost Analyst, Mid' 'Data Engineer (On-Site, Irvine, CA)'
 'Principal Data Analyst' 'District Manager'
 'Quantitative Analytics Senior - Internal Audit (Hybrid - 3 Days in Office)'
 'Clinical Educator' 'Manager-Data Science'
 'Medical Science Liaison, Endocrinology/Rare Disease'
 'Senior Cyber Intelligence Analyst' 'Data Architect II'
 'ML Ops Engineer - HSS Orthopedic Data Innovation Lab'
 'Data Visualization Specialist, Mid' 'Lead Data Scientist'
 'Technical Consultant (Advanced Visualization and Artificial Intelligence )'
 'Manufacturing Production Supervisor'
 'Knowledge Analyst - (Gen) AI and Digital Transformation'
 'Data Visualization Analyst'
 'Tchr of Engineering Technology - Newark School of Data Science and IT 24-25 (NBOE)'
 'Supply Chain Data Analyst (Day Shift) - New Berlin, WI #347106'
 'Territory Business Manager' 'Lead Product Manager - AI Checkout, Tech'
 'Cloud Administrator'
 'Climate Risk Quantitative Analytics Director (Hybrid - 3 Days in Office)'
 'Customer Success Manager' 'AVP, IT SOX Manager'
 'Business Intelligence Analyst' 'Advisor, Data Science & Analytics'
 'Data Science - Leadership'
 'Junior Full Stack Developer (Data Science & AI) - Remote / Hybrid'
 'Data Scientist II' 'Director, Platform Engineering'
 'Sr. Data Analyst, Finance'
 'Financial Crimes Compliance Model Analyst - Remote'
 'Quantitative Analytics Manager - Data Modeling (Hybrid - 3 Days in Office - VA)'
 'Analytics Solution Owner' 'Data Scientist - Mid-level - TS/SCI REQUIRED'
 'Machine Analyst - Service Center'
 'Experienced Registered Nurse, Acute, Hematology/Oncology'
 'Fellowship - Real World Evidence / Clinical Data Science & Evidence'
 'Law Enforcement Data Analyst' 'Associate Product Review Engineer'
 'Junior Data Scientist, Center for Online & Continuing Education'
 'Data Science Engineer' 'Data Science Engineer II'
 'Manager, Product Data Science' 'Senior Data Analyst- New Initiatives'
 'Health Scientist (Data Scientist)' 'Manager, Card Analytics'
 'Vice President, Metrics and Analytics'
 'Medical Information Specialist III' 'Vice President, Analytics Products'
 'Manager of Web Conversion Analytics'
 'Senior Product Manager, Generalist - Remote'
 'Senior Technical Product Manager-AI'
 'Data Analyst - CXD (Advanced Analytics)'
 'Senior Scientist, Data Science, QDI'
 'Quality Systems Data Science Co-Op- Fall 2024' 'Head of Data'
 'Director, Data Science & Artificial Intelligence'
 'Researcher (Data Science/Engineer)' 'Supervisory Data Scientist'
 'Senior Data Engineer (Machine Learning)'
 'Data Analytics Solutions, Associate'
 'Associate Director, Analytics-Credit Cards'
 'Digital Risk and Compliance Lead' 'Data Science Lead'
 'Tchr of Science - Newark School of Data Science and IT 24-25 (NBOE)'
 'Treatment Navigator' 'Data Scientist 192840'
 'Principal Data Scientist, Experimentation'
 'Sr. Reporting and Analytics Specialist' 'Data science manager'
 'Data Scientist, United States - BCG X'
 'AI - Innovation, Delivery and Business Development Leader (Consumer & Retail Focus)'
 'Data Science Manager - Analytics & Insights'
 'Lead Data Science Analyst (multiple openings) - IHM' 'Data Engineer'
 'Senior Analyst, eCommerce Search'
 'Manager, Data Science - Financial Services' 'Python Data Scientist'
 'Director I, Data Science' 'Data Engineers' 'Senior HPC Architect'
 'Director, Business Data Science & Analytics'
 'Tchr of Mathematics - Newark School of Data Science and Information Technology 24-25 (NBOE)'
 'Financial Planning and Analytics Analyst' 'Data Scientist Manager'
 'Applied Scientist (Audio 3D Vision) - $180-$230k'
 'Medical Sales Representative' 'Associate Manager, Data Science'
 'Data Engineer (L5)- Business Intelligence'
 'Data Scientist (Sr.) - U.S. Citizenship Required'
 'Business Analyst/Agilist' 'Senior Manager, Decision Science'
 'Data Modeler - Remote - Multiple Open Positions'
 'Lead Hospital Data Analyst' 'Intelligence Analyst - Junior'
 'Tchr of Computer Science- Newark School of Data Science and Information Technology 24-25 (NBOE)'
 'Director Data Science' 'Manager, Data Science and BI'
 'Senior Financial Data Analyst - Work Comp Claims'
 'Senior Data Scientist - Reinforcement Learning (RLHF)'
 'Python - Big Data'
 'Senior Data Analyst - General Counsel Office of Systems and Analytics'
 'Associate Manager, Marketing Analytics'
 'Inventory Management Data Scientist' 'NLP Researcher'
 'Data Analytics Specialist' 'Senior Advisor for Data Science'
 'Manager, Data Science Platform Engineering' 'Director of Data Science'
 'Robotics Engineer (AI)'
 'Tchr of English- Newark School of Data Science and Information Technology 24-25 (NBOE)']
Number of unique values: 298

○ Q5: For a numerical column of your choice, calculate the mean, median, and
standard deviation.

In [ ]:
numerical_column = df['Company Rating']

mean_value = numerical_column.mean()

median_value = numerical_column.median()

std_deviation = numerical_column.std()

print(f"Mean of '{numerical_column.name}' column: {mean_value}")
print(f"Median of '{numerical_column.name}' column: {median_value}")
print(f"Standard Deviation of '{numerical_column.name}' column: {std_deviation}")

Mean of 'Company Rating' column: 3.8123006833712982
Median of 'Company Rating' column: 3.8
Standard Deviation of 'Company Rating' column: 0.48028144410072426

Q6: Identify any potential outliers in a numerical column of your choice. Explain
your approach.

In [ ]:
Q1 = numerical_column.quantile(0.25)
Q3 = numerical_column.quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = numerical_column[(numerical_column < lower_bound) | (numerical_column > upper_bound)]

print(f"Potential outliers:\n{outliers}")

Potential outliers:
0      2.7
11     1.0
22     1.0
26     2.4
46     2.9
58     1.0
65     2.9
80     1.0
109    4.8
128    5.0
138    2.7
157    5.0
158    2.9
210    2.7
222    5.0
266    4.8
325    4.8
336    5.0
371    5.0
417    5.0
447    2.9
485    5.0
Name: Company Rating, dtype: float64

Q7: Find the correlation between numerical columns and discuss any interesting
relationships.

In [ ]:
numerical_columns = df.select_dtypes(include=['float64', 'int64'])

correlation_matrix = numerical_columns.corr()

print("Correlation Matrix:")
print(correlation_matrix)

Correlation Matrix:
                Position  Company Rating
Position        1.000000        0.105777
Company Rating  0.105777        1.000000

Q8: Group the data by a categorical column and compute the aggregate statistics
(e.g., mean, sum) for a numerical column.

In [11]:

data = {
    'Job Title': ['Engineer', 'Designer', 'Engineer', 'Designer'],
    'Salary': ['$40.00 - $50.00 Per Hour (Employer est.)', '$60.00 - $70.00 Per Hour (Employer est.)', '$55.00 - $65.00 Per Hour (Employer est.)', '$70.00 - $80.00 Per Hour (Employer est.)']
}
df = pd.DataFrame(data)

def convert_salary_to_numeric(salary_str):
    salary_range = salary_str.split(' - ')
    if len(salary_range) == 2:
        min_salary = float(salary_range[0].replace('$', '').replace(' Per Hour (Employer est.)', ''))
        max_salary = float(salary_range[1].replace('$', '').replace(' Per Hour (Employer est.)', ''))
        return (min_salary + max_salary) / 2
    else:
        return float(salary_range[0].replace('$', '').replace(' Per Hour (Employer est.)', ''))

df['Salary'] = df['Salary'].apply(convert_salary_to_numeric)

aggregated_data = df.groupby('Job Title').agg({
    'Salary': ['mean', 'sum']
})

print(aggregated_data)

          Salary
            mean    sum
Job Title
Designer    70.0  140.0
Engineer    52.5  105.0

Q9:: Based on your analysis, provide a brief summary of any insights or patterns
you discovered in the dataset

The overall distribution of company ratings suggests that most companies are rated above average, with ratings clustering around 3.8. The data does not show extreme variation, indicating relative consistency in company evaluations.
The weak correlation between position and company rating implies that job position does not significantly influence the company's overall rating, meaning factors other than the job position might play a larger role in determining company ratings.
These insights can be valuable for understanding the general sentiment towards companies in the dataset and identifying areas for potential deeper analysis, such as exploring other factors that might influence company ratings.